const { app, BrowserWindow, ipcMain } = require('electron');
const assert = require('node:assert/strict');
const { join } = require('node:path');
const { mkdirSync, mkdtempSync, writeFileSync, readFileSync } = require('node:fs');
const { createServer } = require('node:http');
const { randomUUID } = require('node:crypto');
const { spawn } = require('node:child_process');
const { createInterface } = require('node:readline');
const root = join(__dirname, '..');
const legacy = process.env.DSH_COLLAB_FIXTURE_LEGACY === '1';
mkdirSync(join(root, '.test-data'), { recursive: true });
const data = mkdtempSync(join(root, '.test-data/collaboration-native-'));
process.env.DSH_DESKTOP_DATA_DIR = data;
process.env.DSH_DESKTOP_CONFIG_HOME = join(data, 'core');
process.env.DSH_TELEMETRY_DISABLED = '1';
process.env.DSH_COLLAB_FIXTURE_REJECT_WS = '1';
process.env.DSH_COLLAB_FIXTURE_KEY = 'isolated-local-fixture';
app.commandLine.appendSwitch('use-fake-device-for-media-stream');
app.commandLine.appendSwitch('use-fake-ui-for-media-stream');
const relay = spawn(join(root, '.runtime/bin', process.platform === 'win32' ? 'node.exe' : 'node'), ['services/relay/node_modules/tsx/dist/cli.mjs', 'services/relay/test/collab-fixture.ts'], { cwd: root, stdio: ['pipe', 'pipe', 'inherit'] });
const fixture = new Promise((resolve, reject) => { createInterface({ input: relay.stdout }).once('line', line => resolve(JSON.parse(line))); relay.once('error', reject); });
let modelCalls = 0;
const model = createServer(async (req, res) => {
  if (req.url?.endsWith('/models')) { res.setHeader('content-type', 'application/json'); res.end(JSON.stringify({ data: [{ id: 'deepseek-flash', object: 'model' }] })); return; }
  if (!req.url?.endsWith('/messages')) { res.writeHead(404); res.end('{}'); return; }
  let body = ''; for await (const chunk of req) body += chunk;
  const input = JSON.parse(body); modelCalls++;
  // The deterministic model fixture supplies outputs only inside its own disposable run.
  const profile = JSON.parse(readFileSync(join(data, 'core/collaboration/profile.json')));
  const run = Object.values(profile.runs).sort((a, b) => b.startedAt - a.startedAt)[0];
  const cwd = join(data, 'core/collaboration/workspaces', run.id);
  const answer = '# AI 生成方案\n\n使用 `42` 验证。\n\n```python\nprint(42)\n```\n\n| 项目 | 结果 |\n| --- | --- |\n| 检查 | 通过 |\n\n附件：`generated.png`、`result.txt`。';
  writeFileSync(join(cwd, 'result.txt'), 'Fixture output');
  writeFileSync(join(cwd, 'generated.png'), Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1kAAAAASUVORK5CYII=', 'base64'));
  writeFileSync(join(cwd, 'submission.json'), JSON.stringify({ body: answer, verification: 'Isolated fixture', limitations: 'No production model', files: ['generated.png', 'result.txt'] }));
  const attempt = profile.attempts?.[run.attemptId], task = JSON.parse(readFileSync(join(cwd, 'task.json')));
  const waiting = attempt?.executionMode === 'continuous' && attempt.runIds.length !== 2;
  writeFileSync(join(cwd, 'continuation.json'), JSON.stringify({ action: waiting ? 'wait' : 'ready', summary: waiting ? '等待另一个节点补充复现信息。' : '候选已准备好，等待发布。', ...(!waiting ? { contribution: { summary: '完成 42 的隔离验证并提供结果文件。' } } : {}), nextStep: waiting ? '核对新的复现信息后继续验证。' : '', wakeOn: waiting ? ['reply.created'] : [], decisions: (task.pendingEvents ?? []).map(event => ({ eventId: event.id, decision: 'verify', reason: '已在隔离环境核对本次更新。' })) }));
  const usage = { input_tokens: 128, output_tokens: 32 }, message = { id: randomUUID(), type: 'message', role: 'assistant', model: input.model, content: [{ type: 'text', text: answer }], stop_reason: 'end_turn', usage };
  if (!input.stream) { res.setHeader('content-type', 'application/json'); res.end(JSON.stringify(message)); return; }
  res.writeHead(200, { 'content-type': 'text/event-stream' });
  const emit = (type, value) => res.write(`event: ${type}\ndata: ${JSON.stringify({ type, ...value })}\n\n`);
  emit('message_start', { message: { ...message, content: [], stop_reason: null, usage: { ...usage, output_tokens: 0 } } });
  emit('content_block_start', { index: 0, content_block: { type: 'text', text: '' } }); emit('content_block_delta', { index: 0, delta: { type: 'text_delta', text: answer } });
  emit('content_block_stop', { index: 0 }); emit('message_delta', { delta: { stop_reason: 'end_turn' }, usage: { output_tokens: 32 } }); emit('message_stop', {}); res.end();
});
async function boot() {
  await new Promise(resolve => model.listen(0, '127.0.0.1', resolve));
  mkdirSync(join(data, 'core'), { recursive: true });
  writeFileSync(join(data, 'core/desktop.patch.yml'), `- id: llm-deepseek\n  config:\n    baseURL: http://127.0.0.1:${model.address().port}\n    apiKeyEnv: DSH_COLLAB_FIXTURE_KEY\n    maxTokens: 4096\n`);
  writeFileSync(join(data, 'core/settings.yaml'), 'agent-default-model:\n  provider: deepseek-official\n  model: deepseek-flash\n');
  require(join(root, 'dist/main/index.cjs'));
}
const report = { checks: [], errors: [], console: [], artifacts: [], data, legacy };
let finished = false, started = false;
const timer = setTimeout(() => finish(new Error('Collaboration UI timeout')), 180000);
function finish(error) {
  if (finished) return; finished = true; clearTimeout(timer);
  if (error) report.errors.push(String(error.stack ?? error));
  writeFileSync(join(data, 'report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2)); relay.stdin.end(); model.close(); app.quit();
}
app.on('quit', () => { relay.stdin.end(); if (report.errors.length) process.exit(1); });
app.on('web-contents-created', (_, contents) => contents.on('console-message', details => { if (details.level === 'error') report.console.push(details.message); }));
const handlers = new Map(), original = ipcMain.handle.bind(ipcMain);
ipcMain.handle = (channel, callback) => { handlers.set(channel, callback); return original(channel, async (...args) => {
  const result = await callback(...args);
  if (channel === 'desktop:ready' && !started) { started = true; setTimeout(() => run(args[0]).then(() => finish()).catch(async error => {
    report.ui = await args[0].sender.executeJavaScript('document.body.innerText.slice(0,14000)').catch(() => ''); finish(error);
  }), 100); }
  return result;
}); };
async function run(event) {
  const contents = event.sender, window = BrowserWindow.fromWebContents(contents), js = code => contents.executeJavaScript(code, true);
  window.setSize(1220, 900); contents.setBackgroundThrottling(false);
  const until = async (check, message) => { const start = Date.now(); while (Date.now() - start < 20000) { if (await check()) return; await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(message); };
  const click = text => js(`(() => {const b=Array.from(document.querySelectorAll('button')).find(b=>${JSON.stringify([text].flat())}.includes(b.textContent.trim())); if(!b)throw Error('Button missing: '+${JSON.stringify(text)}); b.click();})()`);
  const rpc = (method, args = {}, channel = '/api') => js(`(async()=>{const method=${JSON.stringify(method)},rpcId=crypto.randomUUID(); const r=await fetch(${JSON.stringify(channel + '/' + method)},{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'client-request',rpcId,method,payload:{args:${JSON.stringify(args)}}})});const body=await r.json(); if(!body.result.ok)throw Error(JSON.stringify(body.result.error));return body.result.value;})()`);
  const fill = (selector, value) => js(`(async () => {const el=document.querySelector(${JSON.stringify(selector)}); if(!el)throw Error('Input missing');const proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>requestAnimationFrame(r));})()`);
  const fillLabel = (label, value, scope = 'body') => js(`(async () => {const box=document.querySelector(${JSON.stringify(scope)}),label=Array.from(box.querySelectorAll('label')).find(el=>el.textContent===${JSON.stringify(label)});if(!label)throw Error('Label missing');const el=document.getElementById(label.htmlFor);const proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>requestAnimationFrame(r));})()`);
  const select = (selector, value) => js(`(() => {const el=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const clickIn = (selector, text) => js(`(() => {const b=Array.from(document.querySelector(${JSON.stringify(selector)}).querySelectorAll('button')).find(b=>b.textContent.trim()===${JSON.stringify(text)});if(!b)throw Error('Scoped button missing');b.click();})()`);
  const captureRegion = async (selector, name) => {
    window.show(); window.focus();
    await js(`(async()=>{document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'start',behavior:'instant'});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));})()`);
    const path = join(data, name); writeFileSync(path, (await contents.capturePage()).toPNG()); report.artifacts.push(path);
  };
  const attach = (selector, files) => js(`(() => {const input=document.querySelector(${JSON.stringify(selector)}); if(!input)throw Error('Upload input missing');const list=new DataTransfer();for(const f of ${JSON.stringify(files)}){const bytes=f.base64?Uint8Array.from(atob(f.base64),c=>c.charCodeAt(0)):f.size?new Uint8Array(f.size):f.text;list.items.add(new File([bytes],f.name,{type:f.type||'application/octet-stream'}));}input.files=list.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1kAAAAASUVORK5CYII=';
  await until(() => js(`(() => {const b=Array.from(document.querySelectorAll('button')).find(b=>['继续','Continue','稍后配置','Configure later'].includes(b.textContent));if(b){if(!b.disabled)b.click();return false;}return document.getElementById('root')?.inert===false&&!!document.querySelector('[contenteditable="true"][data-phase="plain"]');})()`), 'Initial UI did not become ready');
  const f = await fixture;
  const stats = async () => (await fetch(f.origin + '/__fixture/status')).json();
  const act = action => handlers.get('desktop:remote-action')(event, action);
  await act({ type: 'configure', config: { relay: f.origin, name: 'Collaboration UI fixture', enabled: false, background: true, sessionOnly: true } });
  const bundles = await rpc('pluginManager/listBundles');
  assert.equal(bundles.find(b => b.name === 'dsh-p2p-collab').enabled, false);
  await click(['插件', 'Plugins']);
  await until(() => js(`!!document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]')`), 'Bundled collaboration plugin is missing from Plugins while disabled');
  assert.equal(await js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]').getAttribute('aria-checked')`), 'false');
  await js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]').click()`);
  await until(async () => (await rpc('pluginManager/listBundles')).find(b=>b.name==='dsh-p2p-collab').enabled,'Plugin did not enable');
  // Enabled is persisted before the async plugin activation registers its RPC route.
  await until(() => js(`(async()=>{
    const r=await fetch('/desktop-collab/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'client-request',rpcId:crypto.randomUUID(),method:'state',payload:{args:{}}})});
    if(r.status===404)return false;
    if(!r.ok)throw Error('Collaboration state HTTP '+r.status);
    const body=await r.json();if(!body.result.ok)throw Error(JSON.stringify(body.result.error));
    return body.result.value.registered===false;
  })()`),'Unregistered state missing');
  assert.equal(await js(`Array.from(document.querySelectorAll('button')).some(b=>b.textContent.trim()==='协作空间')`),false);
  await assert.rejects(rpc('catalog',{},'/desktop-collab'),/注册中继/);
  const identityBeforeRegistration=(await rpc('state',{},'/desktop-collab')).peer.id;
  await js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] button').click()`);
  await until(()=>js(`!!document.querySelector('.desktop-remote-panel input[type=password]')`),'Relay configuration missing from plugin detail');
  await fill('.desktop-remote-panel input[type=url]',f.origin);
  await fill('.desktop-remote-panel input[type=password]',f.code);
  await click('注册电脑');
  await until(() => js(`Array.from(document.querySelectorAll('button')).some(b=>b.textContent.trim()==='协作空间')`), 'Registered collaboration sidebar entry missing');
  assert.equal((await rpc('state',{},'/desktop-collab')).peer.id,identityBeforeRegistration);
  report.checks.push('Plugin detail registers the relay; an unregistered enabled plugin exposes no workspace and rejects collaboration API calls; registration unlocks it without changing identity');
  await click('协作空间');
  await until(() => js(`!!document.querySelector('[data-testid="collab-page"] .collab-task')`), 'Task catalog did not render');
  await until(async () => !!(await rpc('state', {}, '/desktop-collab')).lastSyncAt, 'HTTP message refresh did not complete');
  assert.equal(await js(`!!document.querySelector('.collab-connection')`), false, 'Collaboration must not display connection presence');
  await until(() => js(`(() => { const button = Array.from(document.querySelectorAll('.collab-tabs button')).find(button => button.textContent.trim() === '我的探索'); return !!button && button.disabled === ${legacy}; })()`), legacy ? 'Legacy catalog did not disable the exploration tab' : 'Modern catalog did not enable exploration before opening a task');
  assert.equal(await js(`!!document.querySelector('[data-collab-detail]')`), false, 'Catalog capability detection must not open a task');
  if (legacy) {
    assert.equal((await stats()).legacy, true, 'Legacy gateway mode did not start');
    await js(`Array.from(document.querySelectorAll('.collab-tabs button')).find(button => button.textContent.trim() === '我的探索').click()`);
    assert.equal(await js(`!!document.querySelector('.collab-task') && !document.querySelector('[data-collab-detail]') && Array.from(document.querySelectorAll('.collab-tabs button')).some(button => button.textContent.trim() === '任务广场' && button.getAttribute('aria-selected') === 'true')`), true, 'Clicking the disabled legacy exploration tab must retain the catalog');
    await js(`(() => {
      const original = window.fetch.bind(window); window.__legacyCollabRequests = [];
      window.__restoreLegacyCollabFetch = () => { window.fetch = original; };
      window.fetch = (input, init) => {
        if (String(input).includes('desktop-collab/') && typeof init?.body === 'string') {
          const request = JSON.parse(init.body); window.__legacyCollabRequests.push({ method: request.method, args: request.payload?.args ?? {} });
        }
        return original(input, init);
      };
    })()`);
    const unsupportedButtons = ['开始本机探索', '确认继续探索', '发布验证记录', '正式验收并结束任务', '修订这个候选'];
    const checkUnsupportedControls = async () => {
      assert.equal(await js(`Array.from(document.querySelectorAll('.collab-detail button')).filter(button => ${JSON.stringify(unsupportedButtons)}.includes(button.textContent.trim())).every(button => button.disabled)`), true, 'Legacy relay exposed an enabled exploration, validation, acceptance, or revision action');
      await js(`Array.from(document.querySelectorAll('.collab-detail button')).filter(button => ${JSON.stringify(unsupportedButtons)}.includes(button.textContent.trim())).forEach(button => button.click())`);
    };
    await js(`document.querySelector('.collab-task').click()`);
    await until(() => js(`!!document.querySelector('[data-collab-detail]') && document.querySelector('.collab').innerText.includes('中继待升级：此中继暂不支持持续探索、候选索引、验证与正式验收。任务和讨论仍可使用。')`), 'Legacy task detail or its capability notice did not render');
    assert.ok((await js(`document.querySelector('.collab-detail').innerText`)).includes('验证协作中的缓存 Token 统计'));
    assert.ok((await js(`document.querySelector('[aria-label="任务要求"]').innerText`)).includes('要求版本 1'), 'Legacy task.revision was not used when specRevision was missing');
    assert.equal(await js(`document.querySelector('.collab-thread .collab-pagination span').textContent`), '第 1 页', 'Missing legacy replyOffset corrupted the initial page');
    assert.equal(await js(`document.querySelector('.collab-detail').innerText.includes('NaN')`), false);
    await checkUnsupportedControls();
    await click('修改记录');
    await until(() => js(`document.querySelector('.collab-detail').innerText.includes('最近 20 个版本')`), 'Legacy history support was unnecessarily disabled');
    await click('关注任务');
    await until(() => js(`document.querySelector('.collab-detail').innerText.includes('取消关注')`), 'Legacy task follow failed');
    assert.equal(modelCalls, 0, 'Browsing legacy tasks must not invoke a model');
    report.checks.push('Legacy detail omits specRevision, attempts, validations, decision and replyOffset; task/discussion rendering, revision fallback, first-page numbering and the supported history endpoint remain usable');

    await until(() => js(`!!document.querySelector('[aria-label="回复任务"] textarea:not(:disabled)')`), 'Legacy discussion composer did not load');
    await fill('[aria-label="回复任务"] textarea', '旧版中继普通讨论仍可发送。'); await click('发送回复');
    await until(() => js(`document.querySelector('.collab-thread')?.innerText.includes('旧版中继普通讨论仍可发送。')`), 'Ordinary discussion failed on the legacy relay');
    const legacyCandidate = await rpc('reply', { operationId: randomUUID(), taskId: f.taskId, kind: 'solution', body: '旧版候选仅供讨论，不能使用新版验收或修订。', baseRevision: 1, solution: { verification: '隔离旧版协议检查', limitations: '' } }, '/desktop-collab');
    await click('刷新详情');
    await until(() => js(`!!document.querySelector('[data-reply-id="${legacyCandidate.id}"]')`), 'Legacy solution body did not render');
    await checkUnsupportedControls();
    assert.equal(await js(`!!document.querySelector('.collab-accept select')`), false, 'Legacy relay exposed formal acceptance evidence controls');
    assert.equal(modelCalls, 0, 'Disabled legacy extension controls invoked a model');
    report.checks.push('Legacy ordinary discussion and existing solution content remain available; continuous exploration, candidate indexing, validation, formal acceptance and candidate revision cannot be invoked');

    for (let index = 0; index < 52; index++) assert.equal((await fetch(f.origin + '/__fixture/peer-reply', { method: 'POST' })).status, 200);
    await click('刷新详情');
    await until(() => js(`Array.from(document.querySelectorAll('.collab-thread .collab-pagination button')).some(button => button.textContent === '下一页讨论' && !button.disabled)`), 'Legacy discussion pagination never became available');
    await clickIn('.collab-thread .collab-pagination', '下一页讨论');
    await until(() => js(`document.querySelector('.collab-thread .collab-pagination span').textContent === '第 2 页' && document.querySelectorAll('.collab-thread .collab-reply').length === 4`), 'Legacy next-page request lost its offset when replyOffset was absent');
    assert.equal(await js(`document.querySelector('.collab-detail').innerText.includes('NaN')`), false);
    await clickIn('.collab-thread .collab-pagination', '上一页讨论');
    await until(() => js(`document.querySelector('.collab-thread .collab-pagination span').textContent === '第 1 页' && document.querySelectorAll('.collab-thread .collab-reply').length === 50`), 'Legacy previous-page navigation failed');
    report.checks.push('More than 50 legacy replies paginate forward and backward without replyOffset, undefined requests or NaN page numbers');

    await click('刷新消息');
    await until(async () => (await rpc('state', {}, '/desktop-collab')).unread > 0, 'Legacy sync did not receive unread peer messages');
    const beforeOpen = await rpc('inbox', {}, '/desktop-collab');
    const targetMessage = beforeOpen.items.find(item => !item.read && item.taskId === f.taskId);
    assert.ok(targetMessage, 'Legacy fixture did not supply an unread message');
    assert.equal(targetMessage.subjectId == null && targetMessage.sourceAttemptId == null, true, 'Legacy inbox still exposed modern subject metadata');
    const unreadBeforeOpen = (await rpc('state', {}, '/desktop-collab')).unread;
    await js(`Array.from(document.querySelectorAll('.collab-tabs button')).find(button => button.textContent.startsWith('消息')).click()`);
    await until(() => js(`!!document.querySelector('[data-event-id="${targetMessage.id}"]')`), 'Legacy inbox message did not render');
    await js(`document.querySelector('[data-event-id="${targetMessage.id}"]').click()`);
    await until(() => js(`!!document.querySelector('[data-collab-detail]') && document.querySelector('.collab').innerText.includes('此中继暂不支持逐条已读；本条消息保留未读，可返回消息列表显式全部标记已读。')`), 'Legacy inbox navigation did not explain that the message stays unread');
    assert.equal((await rpc('inbox', {}, '/desktop-collab')).items.find(item => item.id === targetMessage.id).read, false, 'Opening a legacy inbox item silently marked it read');
    assert.equal((await rpc('state', {}, '/desktop-collab')).unread, unreadBeforeOpen);
    assert.equal(await js(`window.__legacyCollabRequests.some(request => request.method === 'read')`), false, 'Opening a legacy inbox item must not issue an automatic read request');
    await js(`Array.from(document.querySelectorAll('.collab-tabs button')).find(button => button.textContent.startsWith('消息')).click()`);
    await until(() => js(`Array.from(document.querySelectorAll('button')).some(button => button.textContent === '全部标记已读')`), 'Legacy explicit mark-all control disappeared');
    await click('全部标记已读');
    await until(async () => (await rpc('state', {}, '/desktop-collab')).unread === 0, 'Legacy explicit mark-all-read failed');
    report.checks.push('Legacy sync/inbox without subject IDs open safely and preserve unread messages without eventIds requests; the explicit mark-all-read action still works');

    await click('任务广场');
    await until(() => js(`!!document.querySelector('.collab-task')`), 'Legacy catalog did not return');
    await js(`document.querySelector('.collab-task').click()`);
    await until(() => js(`!!document.querySelector('[aria-label="回复任务"] textarea:not(:disabled)')`), 'Legacy reply composer did not reopen');
    await js(`document.querySelector('[aria-label="回复任务"] .collab-draft-ai').open = true`);
    await clickIn('[aria-label="回复任务"]', 'AI 起草一次回复');
    let legacyRun;
    await until(async () => { legacyRun = (await rpc('state', {}, '/desktop-collab')).runs.find(run => run.mode === 'reply'); return legacyRun?.status === 'completed'; }, 'One-shot legacy reply drafting did not complete against the isolated model');
    await until(() => js(`document.querySelector('[aria-label="回复任务"] textarea').value.includes('# AI 生成方案')`), 'One-shot legacy reply output did not remain as an editable review draft');
    assert.equal(legacyRun.attemptId, undefined); assert.equal(legacyRun.limits.executionMode, 'manual');
    assert.equal((await rpc('state', {}, '/desktop-collab')).attempts.length, 0, 'Legacy one-shot drafting created a persistent exploration');
    assert.equal(modelCalls, 1, 'Legacy mode must only invoke the isolated model once');
    await new Promise(resolve => setTimeout(resolve, 3200));
    const finalStats = await stats(), requests = await js('window.__legacyCollabRequests');
    assert.deepEqual(finalStats.legacyViolations, [], 'Legacy gateway received an unsupported extension request');
    assert.equal(finalStats.legacyRequests.some(request => /\/(?:candidates|attempts|validations|accept)$/.test(request.path)), false);
    assert.ok(finalStats.legacyResponses.detail > 0 && finalStats.legacyResponses.sync > 0 && finalStats.legacyResponses.inbox > 0, 'Legacy response stripping was not exercised');
    assert.ok(finalStats.legacyRequests.some(request => request.path.endsWith('/history')), 'Legacy supported history was never requested');
    assert.equal(requests.some(request => ['candidates', 'validate', 'accept', 'attempt-resume', 'attempt-withdraw'].includes(request.method) || request.args.replaces || request.args.eventIds !== undefined || request.args.explorationStatus !== undefined), false, 'Renderer invoked a legacy-incompatible RPC');
    assert.deepEqual(requests.filter(request => request.method === 'start').map(request => request.args.mode), ['reply']);
    assert.equal(requests.filter(request => request.method === 'read').length, 1, 'Only the explicit bulk read should reach the host');
    assert.equal(finalStats.attachmentUploads, 0, 'Review-only legacy drafting uploaded output without publication');
    assert.equal(finalStats.collaborationUpgrades, 0);
    assert.equal(modelCalls, 1, 'Legacy background monitoring started another model run');
    await captureRegion('[aria-label="回复任务"]', 'legacy-reply-draft.png');
    await js('window.__restoreLegacyCollabFetch()');
    report.checks.push('Legacy one-shot reply drafting calls only the isolated model once, retains a review draft, creates no attempt and issues no new-protocol RPC or automatic publication');
    return;
  }
  await click('设置');
  await fill('[aria-label="整个探索累计 Token 上限"]', '100000000');
  await fill('[aria-label="整个探索累计时间上限（分钟）"]', '43200'); await click('保存设置');
  await until(() => js(`document.querySelector('[aria-label="协作设置"] [role="status"]')?.textContent==='已保存'`), 'Large budgets did not save');
  assert.deepEqual((await rpc('state', {}, '/desktop-collab')).settings, { maxTokens: 100000000, maxMinutes: 43200, publishMode: 'review', executionMode: 'manual' });
  await fill('[aria-label="整个探索累计 Token 上限"]', '-1'); await click('保存设置');
  await until(() => js(`document.querySelector('[aria-label="协作设置"] [role="status"]')?.textContent.includes('非负整数')`), 'Budget validation did not show a readable error');
  await fill('[aria-label="整个探索累计 Token 上限"]', '100000000'); await click('保存设置');
  await until(() => js(`document.querySelector('[aria-label="协作设置"] [role="status"]')?.textContent==='已保存'`), 'Budget correction did not save');
  await js(`document.querySelector('input[name="collab-execution-mode"][value="continuous"]').click()`);
  await fill('[aria-label="整个探索累计 Token 上限"]', '0'); await fill('[aria-label="整个探索累计时间上限（分钟）"]', '0'); await click('保存设置');
  await until(() => js(`document.querySelector('[aria-label="协作设置"] [role="status"]')?.textContent.includes('至少需要一项有限')`), 'Continuous exploration accepted unlimited budgets');
  await js(`document.querySelector('input[name="collab-execution-mode"][value="manual"]').click()`);
  await fill('[aria-label="整个探索累计 Token 上限"]', '100000000'); await fill('[aria-label="整个探索累计时间上限（分钟）"]', '43200'); await click('保存设置');
  await until(() => js(`document.querySelector('[aria-label="协作设置"] [role="status"]')?.textContent==='已保存'`), 'Settings did not return to manual execution');
  writeFileSync(join(data, 'large-budget-settings.png'), (await contents.capturePage()).toPNG());
  await click('任务广场'); await until(() => js(`!!document.querySelector('.collab-task')`), 'Catalog did not return');
  await js(`document.querySelector('.collab-task').click()`);
  await until(() => js(`!!document.querySelector('[data-collab-detail]')`), 'Task detail did not open');
  assert.ok((await js('document.querySelector(".collab-detail").innerText')).includes('验证协作中的缓存 Token 统计'));
  assert.ok((await rpc('state', {}, '/desktop-collab')).runs.length === 0);
  await click('关注任务'); await until(() => js(`document.querySelector('.collab-detail').innerText.includes('取消关注')`), 'Follow did not persist');
  await click('← 返回列表');
  assert.equal((await fetch(f.origin + '/__fixture/peer-reply', { method: 'POST' })).status, 200, 'Peer fixture reply failed');
  await click('刷新消息');
  await until(() => js(`Array.from(document.querySelectorAll('.collab-tabs button')).some(b=>b.textContent.startsWith('消息 ('))`), 'Manual HTTP refresh did not receive another peer reply');
  await js(`Array.from(document.querySelectorAll('.collab-tabs button')).find(b=>b.textContent.startsWith('消息')).click()`);
  await until(() => js(`!!document.querySelector('.collab-task.unread')`), 'Unread message did not render');
  await js(`document.querySelector('.collab-task.unread').click()`);
  await until(() => js(`document.querySelector('.collab-thread')?.innerText.includes('另一个节点已补充复现信息。')`), 'Received reply did not open');
  await js(`(() => {
    const original = window.fetch.bind(window); window.__collabVoice = { calls: 0, replies: 0, wave: false };
    window.__restoreCollabFetch = () => { window.fetch = original; };
    window.fetch = async (input, init) => {
      const url = String(input);
      if (url.endsWith('desktop-collab/reply')) window.__collabVoice.replies++;
      if (!url.endsWith('api/speech/catalog') && !url.endsWith('api/speech/transcribe')) return original(input, init);
      const request = JSON.parse(init.body); let value;
      if (url.endsWith('/catalog')) value = { providers: [{ id: 'fixture', preparation: { phase: 'ready' } }], selection: { providerId: 'fixture', language: 'zh' }, maxAudioBytes: 1048576, maxDurationSeconds: 10 };
      else { window.__collabVoice.calls++; window.__collabVoice.wave = atob(request.payload.args.request.audioBase64).startsWith('RIFF'); value = { text: '语音只追加到草稿' }; }
      return new Response(JSON.stringify({ type: 'server-response', rpcId: request.rpcId, result: { ok: true, value } }), { headers: { 'content-type': 'application/json' } });
    };
  })()`);
  await fill('[aria-label="回复任务"] textarea', '已输入的草稿');
  await js(`document.querySelector('[aria-label="语音输入：回复内容"]').click()`);
  await until(() => js(`!!document.querySelector('[aria-label="结束：回复内容"]')`), 'Collaboration microphone did not start');
  await new Promise(resolve => setTimeout(resolve, 450));
  await js(`document.querySelector('[aria-label="结束：回复内容"]').click()`);
  await until(() => js(`document.querySelector('[aria-label="回复任务"] textarea').value.includes('语音只追加到草稿')`), 'Speech transcript did not append');
  assert.deepEqual(await js('window.__collabVoice'), { calls: 1, replies: 0, wave: true });
  assert.ok((await js(`document.querySelector('[aria-label="回复任务"] textarea').value`)).startsWith('已输入的草稿'));
  await js('window.__restoreCollabFetch()');
  report.checks.push('Collaboration microphone captures a fake Chromium device, sends PCM WAV to a stub speech service and appends text without publishing');
  await fill('[aria-label="回复任务"] textarea', '本机用户确认：正在补充复现条件。 https://example.com/shared-artifact.zip');
  await attach('[aria-label="回复任务"] input[type="file"]', [{ name: 'not-uploaded.txt', text: 'valid file before oversized file' }, { name: 'too-large.zip', size: 8 * 1024 * 1024 + 1 }]);
  await until(() => js(`document.querySelector('[aria-label="回复任务"] [role="alert"]')?.textContent.includes('下载链接')`), 'Oversized reply attachment did not suggest a link');
  assert.equal((await stats()).attachmentUploads, 0, 'Oversized selection must fail before uploading any member');
  await attach('[aria-label="回复任务"] input[type="file"]', [{ name: 'reply-image.png', base64: png, type: 'image/png' }, { name: 'boundary-8MiB.bin', size: 8 * 1024 * 1024 }]);
  await until(() => js(`document.querySelectorAll('[aria-label="回复任务"] .collab-upload > span').length===2`), 'Valid reply image and 8 MiB boundary attachment did not upload');
  await fetch(f.origin + '/__fixture/drop-next-reply', { method: 'POST' });
  await click('发送回复');
  await until(() => js(`document.querySelector('[aria-label="回复任务"] [role="alert"]')?.textContent.includes('fixture_response_lost')`), 'Lost response did not report an unconfirmed send');
  assert.ok((await js(`document.querySelector('[aria-label="回复任务"] textarea').value`)).includes('正在补充复现条件'));
  assert.equal(await js(`document.querySelectorAll('[aria-label="回复任务"] .collab-upload > span').length`), 2);
  await click('发送回复');
  await until(() => js(`document.querySelector('.collab-thread').innerText.includes('本机用户确认：正在补充复现条件。')`), 'Human reply did not appear');
  assert.equal((await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).replies.filter(r => r.body.includes('本机用户确认')).length, 1, 'Retry after a lost response duplicated the reply');
  assert.equal(await js(`document.querySelector('.collab-thread a')?.getAttribute('href')`), 'https://example.com/shared-artifact.zip');
  await js(`document.querySelector('[aria-label="预览图片 reply-image.png"]').click()`);
  await until(() => js(`document.querySelector('.collab-thread img')?.naturalWidth>0`), 'Uploaded reply image preview did not render');
  writeFileSync(join(data, 'reply-attachments.png'), (await contents.capturePage()).toPNG());
  await clickIn('.collab-tabs', '我的探索');
  await until(() => js(`!!document.querySelector('.collab-empty')&&!document.querySelector('.collab-task')`), 'An ordinary discussion reply was incorrectly listed as an exploration');
  assert.equal(modelCalls, 0, 'Browsing, following and replying must not call a model');
  await click('任务广场'); await until(() => js(`!!document.querySelector('.collab-task')`), 'Catalog missing after exploration filter'); await js(`document.querySelector('.collab-task').click()`);
  await until(() => js(`!!document.querySelector('[aria-label="我的探索"]')`), 'Exploration section missing');
  assert.deepEqual(await js(`Array.from(document.querySelectorAll('[aria-label="任务分区"] button')).map(button=>button.textContent)`), ['任务概览', '候选方案', '讨论', '我的探索']);
  await fillLabel('公开探索方向（可选）', '公开：检查缓存计数', '[aria-label="我的探索"]');
  await fillLabel('本机补充要求（不公开）', '私有：只使用隔离夹具工作目录', '[aria-label="我的探索"]');
  await click('开始本机探索');
  await until(() => js(`document.querySelector('[aria-label="回复任务"] textarea')?.value.includes('# AI 生成方案')`), 'Reviewed AI result did not automatically populate the editor');
  assert.equal((await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).replies.filter(r => r.actor === 'dsh').length, 0, 'Review mode published before review');
  const sharedAttempt = (await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).attempts[0];
  assert.equal(sharedAttempt.direction, '公开：检查缓存计数');
  assert.equal(JSON.stringify(sharedAttempt).includes('私有：'), false, 'Private launch instructions appeared in public progress');
  assert.equal(await js(`document.querySelector('[aria-label="本机探索历史"]').open`), false, 'Run history should start collapsed');
  assert.equal(await js(`document.querySelectorAll('[aria-label="AI 生成附件"] > span').length`), 2);
  await js(`document.querySelector('[aria-label="移除 result.txt"]').click()`);
  await fill('[aria-label="回复任务"] textarea', '# 人工审核后的方案\n\n已修改 AI 正文，保留图片附件。');
  await click('发布候选');
  await until(() => js(`document.querySelector('.collab-thread')?.innerText.includes('人工审核后的方案')`), 'Reviewed AI result did not publish');
  const reviewed = (await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).replies.find(r => r.body.includes('人工审核后的方案'));
  assert.deepEqual(reviewed.attachments.map(file => file.name), ['generated.png']);
  assert.equal(reviewed.actor, 'dsh');
  await click('设置');
  await js(`document.querySelector('input[name="collab-publish-mode"][value="auto"]').click()`); await click('保存设置');
  await until(async () => (await rpc('state', {}, '/desktop-collab')).settings.publishMode === 'auto', 'Auto mode did not save');
  await click('任务广场'); await until(() => js(`!!document.querySelector('.collab-task')`), 'Catalog missing'); await js(`document.querySelector('.collab-task').click()`);
  await until(() => js(`document.querySelector('[aria-label="本次探索发布方式"]')?.value==='auto'`), 'Default publishing mode was not applied to new exploration controls');
  assert.ok(await js(`Array.from(document.querySelectorAll('[data-attempt-id]')).some(element=>element.innerText.includes('填入草稿待审核'))`), 'Existing exploration lost its launch-time publishing mode');
  await select('[aria-label="本次推进方式"]', 'continuous');
  await js(`document.querySelector('[aria-label="回复任务"] .collab-draft-ai').open=true`);
  assert.equal(await js(`Array.from(document.querySelectorAll('[aria-label="我的探索"] button')).some(button=>button.textContent==='AI 起草一次回复')`), false, 'One-shot drafting belongs beside the reply editor');
  const attemptsBeforeDraft = (await rpc('state', {}, '/desktop-collab')).attempts.length;
  await clickIn('[aria-label="回复任务"]', 'AI 起草一次回复');
  await until(() => js(`document.querySelector('.collab-detail')?.innerText.includes('AI 已自动发布正文和附件')`), 'AI did not auto publish');
  const automatic = (await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).replies.filter(r => r.body.includes('# AI 生成方案'));
  assert.equal(automatic.length, 1); assert.equal(automatic[0].attachments.length, 2);
  assert.equal((await rpc('state', {}, '/desktop-collab')).attempts.length, attemptsBeforeDraft, 'One-shot reply drafting must not create a persistent exploration');
  assert.equal((await rpc('state', {}, '/desktop-collab')).runs.find(run => run.mode === 'reply').limits.executionMode, 'manual');
  await until(() => js(`!!document.querySelector('.collab-thread .collab-prose table')`), 'Markdown table did not render');
  assert.ok(await js(`Array.from(document.querySelectorAll('.collab-thread .collab-prose code')).some(e=>e.textContent.includes('print(42)'))`), 'Fenced Python code did not render');
  assert.equal(modelCalls, 2);
  await js(`Array.from(document.querySelectorAll('.collab-thread .collab-reply')).at(-1).scrollIntoView({block:'start'})`);
  await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
  writeFileSync(join(data, 'markdown-ai-solution.png'), (await contents.capturePage()).toPNG());
  await click('设置'); await js(`document.querySelector('input[name="collab-publish-mode"][value="manual"]').click()`); await click('保存设置');
  await until(async () => (await rpc('state', {}, '/desktop-collab')).settings.publishMode === 'manual', 'Manual mode did not save');
  await click('任务广场'); await until(() => js(`!!document.querySelector('.collab-task')`), 'Catalog missing'); await js(`document.querySelector('.collab-task').click()`);
  await until(() => js(`!!document.querySelector('[aria-label="回复任务"] textarea')`), 'Manual reply composer missing');
  assert.equal(await js(`Array.from(document.querySelectorAll('[aria-label="回复任务"] button')).some(b=>b.textContent==='AI 起草一次回复'&&!b.disabled)`), true, 'Local-only publishing must still allow AI generation');
  await select('[aria-label="本次推进方式"]', 'continuous'); await click('开始本机探索');
  let continuous;
  await until(async () => { continuous = (await rpc('state', {}, '/desktop-collab')).attempts.find(attempt => attempt.executionMode === 'continuous'); return continuous?.status === 'waiting'; }, 'Continuous exploration did not show a waiting checkpoint');
  const attemptSelector = `[data-attempt-id="${continuous.id}"]`;
  await until(() => js(`document.querySelector(${JSON.stringify(attemptSelector)})?.innerText.includes('等待新信息')`), 'Waiting participation state did not render');
  assert.equal(await js(`document.querySelector('[aria-label="回复任务"] textarea').value`), '', 'Manual publishing must leave the existing draft unchanged');
  await clickIn(attemptSelector, '暂停探索');
  await until(async () => (await rpc('state', {}, '/desktop-collab')).attempts.find(attempt => attempt.id === continuous.id).desiredState === 'paused', 'Pause did not persist');
  const callsBeforePausedMessage = modelCalls;
  await fetch(f.origin + '/__fixture/peer-reply', { method: 'POST' }); await click('刷新消息');
  await until(async () => (await rpc('state', {}, '/desktop-collab')).attempts.find(attempt => attempt.id === continuous.id).pendingEvents.length > 0, 'Paused attempt did not retain new events');
  await new Promise(resolve => setTimeout(resolve, 3500));
  assert.equal(modelCalls, callsBeforePausedMessage, 'An external message resumed the paused attempt');
  await until(() => js(`document.querySelector(${JSON.stringify(attemptSelector)})?.innerText.includes('只有你恢复')`), 'Paused state did not explain explicit resume');
  await captureRegion(attemptSelector, 'task-workbench-paused.png');
  await js(`document.querySelector(${JSON.stringify(attemptSelector + ' .collab-resume>summary')}).click()`);
  await fillLabel('继续探索的下一步', '核对新增复现信息并给出候选。', attemptSelector);
  await clickIn(attemptSelector, '确认继续探索');
  await until(async () => { continuous = (await rpc('state', {}, '/desktop-collab')).attempts.find(attempt => attempt.id === continuous.id); return continuous.status === 'ready' && continuous.runIds.length === 2; }, 'Explicit resume did not complete a second round');
  const resumedRun = continuous.runIds[1];
  await until(() => js(`document.querySelectorAll('[aria-label="本机探索历史"] [data-run-id]').length>=4`), 'Multiple runs did not remain available in history');
  await js(`document.querySelector('[aria-label="本机探索历史"]').open=true`);
  await js(`document.querySelector('[data-run-id="${resumedRun}"] button').click()`);
  await until(() => js(`!!document.querySelector('[data-selected-run="${resumedRun}"]')`), 'Selecting a historical run did not switch its result');
  await click('选作草稿并检查附件');
  await until(() => js(`document.querySelector('[aria-label="回复任务"] textarea').value.includes('# AI 生成方案')`), 'Manual generation could not be imported as a reviewed draft');
  assert.ok(continuous.usedTokens > 0, 'Participation did not aggregate settled usage');
  await click('发布候选');
  await until(async () => { continuous = (await rpc('state', {}, '/desktop-collab')).attempts.find(attempt => attempt.id === continuous.id); return !!continuous.candidateReplyId && continuous.status === 'submitted'; }, 'Continuous candidate was not recorded before the next round');
  const continuousCandidateId = continuous.candidateReplyId;
  await until(() => js(`!!document.querySelector(${JSON.stringify(attemptSelector + ' .collab-resume')})`), 'Submitted exploration cannot be continued');
  await js(`document.querySelector(${JSON.stringify(attemptSelector + ' .collab-resume')}).open=true`);
  await fillLabel('继续探索的下一步', '候选之后整理一条局部进展，等待更多信息。', attemptSelector);
  await clickIn(attemptSelector, '确认继续探索');
  await until(async () => { continuous = (await rpc('state', {}, '/desktop-collab')).attempts.find(attempt => attempt.id === continuous.id); return continuous.status === 'waiting' && continuous.runIds.length === 3; }, 'Post-candidate discussion round did not reach its wait checkpoint');
  const discussionRunId = continuous.runIds[2], discussionRun = await rpc('run', { runId: discussionRunId }, '/desktop-collab');
  assert.equal(discussionRun.replacesReplyId, continuousCandidateId, 'Fixture must exercise a run that knows its preceding candidate');
  await until(() => js(`!!document.querySelector('[data-run-id="${discussionRunId}"] button')`), 'Post-candidate run missing from history');
  await js(`document.querySelector('[data-run-id="${discussionRunId}"] button').click()`);
  await until(() => js(`!!document.querySelector('[data-selected-run="${discussionRunId}"]')`), 'Post-candidate run result did not open');
  await click('选作草稿并检查附件');
  await until(() => js(`Array.from(document.querySelectorAll('[aria-label="回复任务"] button')).some(button=>button.textContent==='贡献或讨论'&&button.getAttribute('aria-pressed')==='true')`), 'A wait checkpoint must import as a discussion draft');
  assert.equal(await js(`document.querySelector('[aria-label="回复任务"]').innerText.includes('此提交会保留原方案')`), false, 'Discussion import incorrectly retained a candidate replacement link');
  await fill('[aria-label="回复任务"] textarea', '候选之后的局部进展，只作为讨论发布。'); await click('发送回复');
  let postCandidateDiscussion;
  await until(async () => { postCandidateDiscussion = (await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).replies.find(reply => reply.body === '候选之后的局部进展，只作为讨论发布。'); return !!postCandidateDiscussion; }, 'Imported discussion failed to publish without an extra kind-switching step');
  assert.equal(postCandidateDiscussion.kind, 'message'); assert.equal(postCandidateDiscussion.replaces, null);
  report.checks.push('After publishing a candidate, a subsequent wait-stage run imports directly as discussion without a replacement link and publishes successfully without toggling draft kind');
  await clickIn(attemptSelector, '退出探索');
  await until(async () => (await rpc('state', {}, '/desktop-collab')).attempts.find(attempt => attempt.id === continuous.id).desiredState === 'withdrawn', 'Withdrawing did not end ongoing participation');
  report.checks.push('Execution and publishing modes are independent; continuous mode needs a finite budget; paused attempts keep external updates without running; explicit resume preserves multiple runs and cumulative usage; manual AI results can be selected as drafts');
  report.checks.push('Review mode fills editable Markdown and generated files; reviewer edits text and removes an attachment; auto mode publishes exactly once with files');
  await click('发布任务');
  await until(() => js(`!!document.querySelector('[aria-label="发布任务"] textarea:not(:disabled)')`), 'Task composer did not load');
  assert.equal(await js(`document.querySelector('[aria-label="发布任务"] details').open`), false);
  await fill('[aria-label="发布任务"] textarea', '可复现的协作任务\n\n测试任务描述：请检查界面、草稿和版本记录。');
  const uploadsBeforeTask = (await stats()).attachmentUploads;
  await attach('[aria-label="发布任务"] input[type="file"]', Array.from({ length: 9 }, (_, i) => ({ name: `file-${i}.txt`, text: 'fixture' })));
  await until(() => js(`document.querySelector('[aria-label="发布任务"] [role="alert"]')?.textContent.includes('最多附带 8 个')`), 'Attachment count limit missing');
  assert.equal((await stats()).attachmentUploads, uploadsBeforeTask);
  await attach('[aria-label="发布任务"] input[type="file"]', [{ name: 'task-image.png', base64: png, type: 'image/png' }, { name: 'reproduction.txt', text: 'Reproduction attachment' }]);
  await until(() => js(`document.querySelectorAll('[aria-label="发布任务"] .collab-upload > span').length===2`), 'Task attachments did not upload');
  await until(() => js(`Array.from(document.querySelectorAll('[aria-label="发布任务"] button')).some(b=>b.textContent==='发布任务'&&!b.disabled)`), 'Publish button stayed disabled');
  await js(`Array.from(document.querySelectorAll('[aria-label="发布任务"] button')).find(b=>b.textContent==='发布任务').click()`);
  await until(() => js(`document.querySelector('[data-collab-detail] h1')?.textContent==='可复现的协作任务'`), 'Published task did not open');
  await js(`document.querySelector('[aria-label="预览图片 task-image.png"]').click()`);
  await until(() => js(`document.querySelector('.collab-detail > section img')?.naturalWidth>0`), 'Task image preview did not render');
  await click('编辑任务');
  await fill('[aria-label="编辑任务"] textarea', '已补充验收数据，保留第一版内容。');
  await click('保存新版本');
  await until(() => js(`document.querySelector('.collab-detail').innerText.includes('版本 2')`), 'Revision did not update');
  await click('修改记录');
  await until(() => js(`document.querySelector('.collab-detail').innerText.includes('最近 20 个版本')`), 'Revision history missing');
  assert.ok((await js(`Array.from(document.querySelectorAll('.collab-detail details')).map(e=>e.textContent).join(' ')`)).includes('测试任务描述：请检查界面、草稿和版本记录。'));
  assert.ok((await js(`document.querySelector('[aria-label="任务要求"]').innerText`)).includes('尚未约定'), 'Missing acceptance criteria must be visible');
  const ownTaskId = await js(`document.querySelector('[data-collab-detail]').getAttribute('data-collab-detail')`);
  const repliesBeforeSharing = (await rpc('detail', { taskId: ownTaskId }, '/desktop-collab')).task.replyCount;
  await click('分享阻塞');
  assert.ok((await js(`document.querySelector('[aria-label="回复任务"] textarea').value`)).includes('遇到的阻塞：'));
  assert.equal((await rpc('detail', { taskId: ownTaskId }, '/desktop-collab')).task.replyCount, repliesBeforeSharing, 'A share template must remain an editable draft until sent');
  await click('提交候选方案'); await fill('[aria-label="回复任务"] textarea', '第一版候选，需要按当前要求验证。'); await click('发布候选');
  let ownDetail, firstCandidate;
  await until(async () => { ownDetail = await rpc('detail', { taskId: ownTaskId }, '/desktop-collab'); firstCandidate = ownDetail.replies.find(reply => reply.body.includes('第一版候选')); return !!firstCandidate; }, 'Candidate did not publish');
  assert.equal(ownDetail.task.status, 'open', 'A candidate must not close task exploration');
  let validationSelector = `[data-candidate-validation="${firstCandidate.id}"]`;
  await until(() => js(`!!document.querySelector(${JSON.stringify(validationSelector)})`), 'Candidate validation controls did not render');
  assert.equal(await js(`document.querySelector(${JSON.stringify(validationSelector)}).querySelector('.collab-accept button').disabled`), true, 'Acceptance must require a validation record');
  await js(`document.querySelector(${JSON.stringify(validationSelector + ' .collab-optional>summary')}).click()`);
  await fillLabel('验证方法', '检查第一版候选', validationSelector); await fillLabel('验证环境', '隔离 UI fixture', validationSelector); await fillLabel('验证证据', '第一版检查通过，证据仅用于隔离测试。', validationSelector); await clickIn(validationSelector, '发布验证记录');
  await until(() => js(`document.querySelector(${JSON.stringify(validationSelector)}).innerText.includes('验证通过 · 提交者自验')`), 'Validation provenance did not distinguish submitter self-check');
  await click('编辑任务'); await fill('[aria-label="编辑任务"] textarea', '第三版要求：增加新的验证条件。'); await click('保存新版本');
  await until(() => js(`document.querySelector(${JSON.stringify(validationSelector)}).innerText.includes('已过期')`), 'A task specification change did not expire old validation');
  assert.equal(await js(`document.querySelector(${JSON.stringify(validationSelector)}).querySelector('.collab-accept select').options.length`), 1, 'Old validation remained selectable for acceptance');
  await fill('[aria-label="回复任务"] textarea', '已有未发送的讨论草稿，不能被修订操作覆盖。');
  await clickIn(`[data-reply-id="${firstCandidate.id}"]`, '修订这个候选');
  assert.equal(await js(`document.querySelector('[aria-label="回复任务"] textarea').value`), '已有未发送的讨论草稿，不能被修订操作覆盖。');
  await clickIn('[aria-label="回复任务"]', '保留当前草稿');
  assert.equal(await js(`document.querySelector('[aria-label="回复任务"] textarea').value`), '已有未发送的讨论草稿，不能被修订操作覆盖。');
  await clickIn(`[data-reply-id="${firstCandidate.id}"]`, '修订这个候选'); await clickIn('[aria-label="回复任务"]', '替换当前草稿');
  assert.ok((await js(`document.querySelector('[aria-label="回复任务"] textarea').value`)).includes('第一版候选'));
  await clickIn('[aria-label="回复任务"]', '贡献或讨论');
  assert.equal(await js(`document.querySelector('[aria-label="回复任务"]').innerText.includes('此提交会保留原方案')`), false, 'Switching to discussion must clear the candidate replacement link');
  await clickIn(`[data-reply-id="${firstCandidate.id}"]`, '修订这个候选'); await clickIn('[aria-label="回复任务"]', '替换当前草稿');
  await fill('[aria-label="回复任务"] textarea', '第二版候选，包含新增验证条件。'); await click('发布候选');
  let secondCandidate;
  await until(async () => { ownDetail = await rpc('detail', { taskId: ownTaskId }, '/desktop-collab'); secondCandidate = ownDetail.replies.find(reply => reply.replaces === firstCandidate.id); return !!secondCandidate; }, 'Candidate revision did not preserve its predecessor');
  await until(() => js(`document.querySelector(${JSON.stringify(validationSelector)}).innerText.includes('已有修订版本')`), 'Superseded candidate was not labelled');
  assert.equal(await js(`!!document.querySelector(${JSON.stringify(validationSelector)}).querySelector('.collab-accept')`), false, 'Superseded candidate still offered acceptance');
  validationSelector = `[data-candidate-validation="${secondCandidate.id}"]`;
  await js(`document.querySelector(${JSON.stringify(validationSelector + ' .collab-optional>summary')}).click()`);
  await select(validationSelector + ' [aria-label="验证结论"]', 'inconclusive');
  await fillLabel('验证方法', '先检查证据完整性', validationSelector); await fillLabel('验证环境', '隔离 UI fixture', validationSelector); await fillLabel('验证证据', '第一次验证缺少一项证据。', validationSelector); await clickIn(validationSelector, '发布验证记录');
  await until(() => js(`Array.from(document.querySelector(${JSON.stringify(validationSelector)}).querySelectorAll('summary')).some(element=>element.textContent.startsWith('结论不充分 ·'))`), 'Inconclusive validation did not render');
  assert.equal(await js(`document.querySelector(${JSON.stringify(validationSelector)}).querySelector('.collab-accept select').options.length`), 1, 'Inconclusive validation was offered as acceptance evidence');
  await fillLabel('验证方法', '复查当前全部要求', validationSelector); await fillLabel('验证环境', '隔离 UI fixture', validationSelector); await fillLabel('验证证据', '当前要求全部通过，附有可复核的测试证据。', validationSelector); await clickIn(validationSelector, '发布验证记录');
  let passedValidation;
  await until(async () => { ownDetail = await rpc('detail', { taskId: ownTaskId }, '/desktop-collab'); passedValidation = ownDetail.validations.find(validation => validation.replyId === secondCandidate.id && validation.outcome === 'passed'); return !!passedValidation; }, 'Passing validation was not saved');
  await until(() => js(`document.querySelector(${JSON.stringify(validationSelector)}).querySelector('.collab-accept select').options.length===2`), 'Current passing validation was not available');
  await select(validationSelector + ' [aria-label="验收依据"]', passedValidation.id);
  await js(`(()=>{const box=document.querySelector(${JSON.stringify(validationSelector)});box.querySelector('.collab-optional').open=false;Array.from(box.querySelectorAll('details')).find(element=>element.querySelector('summary')?.textContent.startsWith('验证通过 ·')).open=true;})()`);
  await captureRegion(`[data-reply-id="${secondCandidate.id}"]`, 'task-workbench-validation.png');
  await clickIn(validationSelector, '正式验收并结束任务');
  await until(() => js(`document.querySelector(${JSON.stringify(validationSelector)}).innerText.includes('发布者已正式验收')`), 'Author acceptance did not show its final decision');
  ownDetail = await rpc('detail', { taskId: ownTaskId }, '/desktop-collab');
  assert.equal(ownDetail.task.status, 'resolved'); assert.equal(ownDetail.decision.validationId, passedValidation.id); assert.equal(ownDetail.decision.replyId, secondCandidate.id);
  report.checks.push('Task requirements stay visible; candidates keep tasks open; self-check provenance is explicit; changed requirements expire validation; superseded candidates and inconclusive checks cannot be accepted; author acceptance records a chosen passing validation');
  report.checks.push('Public direction is distinct from private launch instructions; old explorations retain publishing settings; one-shot AI drafting lives in the reply editor and creates no exploration; run history starts collapsed; sharing and candidate revisions preserve existing drafts until explicitly replaced');
  const bounds = await js(`(()=>{const e=document.querySelector('.collab');return {width:e.clientWidth,scroll:e.scrollWidth,height:e.clientHeight};})()`);
  assert.ok(bounds.scroll <= bounds.width + 1, 'Collaboration page overflows horizontally');
  window.show(); window.focus();
  await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
  writeFileSync(join(data, 'task-detail.png'), (await contents.capturePage()).toPNG());
  await click('任务广场');
  await until(() => js(`document.querySelectorAll('.collab-task').length===2`), 'Catalog did not refresh after publish');
  await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
  writeFileSync(join(data, 'task-catalog.png'), (await contents.capturePage()).toPNG());
  report.checks.push('Task publishing, author editing, preserved revision history and refreshed catalog pass in actual Electron UI; screenshots captured without horizontal overflow');
  // Fill more than one discussion page, then prove index and inbox navigation use their exact subjects.
  for (let index = 0; index < 53; index++) assert.equal((await fetch(f.origin + '/__fixture/peer-reply', { method: 'POST' })).status, 200);
  const pagedCandidate = await rpc('reply', { operationId: randomUUID(), taskId: f.taskId, kind: 'solution', body: '跨页候选：可以从索引直接找到此结果。', baseRevision: 1, solution: { verification: '隔离跨页检查', limitations: '' } }, '/desktop-collab');
  await click('刷新消息');
  const beforeOpen = await rpc('inbox', {}, '/desktop-collab');
  const targetMessage = beforeOpen.items.find(item => !item.read && item.taskId === f.taskId && item.kind === 'reply.created');
  const otherMessage = beforeOpen.items.find(item => !item.read && item.taskId === f.taskId && item.id !== targetMessage?.id);
  assert.ok(targetMessage && otherMessage, 'Fixture needs at least two unread updates on the same task');
  await js(`Array.from(document.querySelectorAll('.collab-task')).find(element=>element.innerText.includes('验证协作中的缓存 Token 统计')).click()`);
  await until(() => js(`document.querySelector('[data-collab-detail]')?.dataset.collabDetail===${JSON.stringify(f.taskId)}`), 'Original task did not reopen');
  assert.equal((await rpc('inbox', {}, '/desktop-collab')).items.find(item => item.id === targetMessage.id).read, false, 'Opening the task overview must not clear unseen messages');
  await until(() => js(`!!document.querySelector('[data-candidate-id="${pagedCandidate.id}"]')`), 'Candidate beyond the first discussion page was missing from its independent index');
  await js(`document.querySelector('[data-candidate-id="${pagedCandidate.id}"]').click()`);
  await until(() => js(`document.querySelector('[data-reply-id="${pagedCandidate.id}"]')?.dataset.highlighted==='true'`), 'Candidate index did not locate and highlight the correct discussion page');
  assert.equal(await js(`document.querySelector('.collab-thread .collab-pagination span').textContent`), '第 2 页');
  assert.equal((await rpc('inbox', {}, '/desktop-collab')).items.find(item => item.id === targetMessage.id).read, false, 'Candidate navigation must not mark unrelated notifications read');
  await captureRegion(`[data-reply-id="${pagedCandidate.id}"]`, 'candidate-cross-page.png');
  await js(`Array.from(document.querySelectorAll('.collab-tabs button')).find(button=>button.textContent.startsWith('消息')).click()`);
  await until(() => js(`!!document.querySelector('[data-event-id="${targetMessage.id}"]')`), 'Target inbox event did not render');
  await js(`document.querySelector('[data-event-id="${targetMessage.id}"]').click()`);
  await until(() => js(`document.querySelector('[data-reply-id="${targetMessage.subjectId}"]')?.dataset.highlighted==='true'`), 'Inbox did not locate the exact event subject');
  await until(async () => (await rpc('inbox', {}, '/desktop-collab')).items.find(item => item.id === targetMessage.id).read, 'Opening a located message did not mark that event read');
  assert.equal((await rpc('inbox', {}, '/desktop-collab')).items.find(item => item.id === otherMessage.id).read, false, 'Opening one message cleared another unread event from the same task');
  await js(`Array.from(document.querySelectorAll('.collab-tabs button')).find(button=>button.textContent.startsWith('消息')).click()`);
  await until(() => js(`Array.from(document.querySelectorAll('button')).some(button=>button.textContent==='全部标记已读')`), 'Explicit bulk read control missing');
  await click('全部标记已读');
  await until(async () => (await rpc('state', {}, '/desktop-collab')).unread === 0, 'Explicit mark-all-read did not clear notifications');
  report.checks.push('The independent candidate index locates a candidate beyond 50 discussion rows; opening an overview or candidate leaves notifications unread; opening an inbox event highlights its subject and marks only that event; explicit mark-all-read still works');
  assert.equal((await stats()).collaborationUpgrades, 0);
  report.checks.push('100 million Token / 30-day budgets save; HTTP-only manual inbox refresh receives peer replies while collaboration WebSocket is rejected');
  report.checks.push('Task/reply images and attachments upload and preview; exact 8 MiB upload succeeds; oversized batch and ninth file are rejected before upload; a lost reply response preserves its draft and retry creates one reply');
  await click(['插件', 'Plugins']);
  await until(() => js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]')?.getAttribute('aria-checked')==='true'`), 'Enabled collaboration switch missing');
  await js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]').click()`);
  await until(async () => !(await rpc('pluginManager/listBundles')).find(b => b.name === 'dsh-p2p-collab').enabled, 'Plugin did not disable');
  await until(() => js(`!!document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"][aria-checked="false"]')&&!Array.from(document.querySelectorAll('button')).some(b=>b.textContent.trim()==='协作空间')`), 'Disabled plugin disappeared from Plugins or left an active sidebar');
  report.checks.push('Actual Plugins switch disables collaboration and retains its card for later re-enabling');
  await js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]').click()`);
  await until(()=>js(`Array.from(document.querySelectorAll('button')).some(b=>b.textContent.trim()==='协作空间')`),'Registered workspace did not return after re-enabling');
  await click('协作空间');
  await until(()=>js(`!!document.querySelector('[data-testid="collab-page"] .collab-task')`),'Re-enabled catalog missing');
  const identityBeforeRevocation=(await rpc('state',{},'/desktop-collab')).peer.id;
  await rpc('draft-put',{key:'registration-fixture',value:{body:'Keep across unregister'}},'/desktop-collab');
  await act({type:'unregister'});
  await until(()=>js(`!Array.from(document.querySelectorAll('button')).some(b=>b.textContent.trim()==='协作空间')&&!document.querySelector('[data-testid="collab-page"]')`),'Revoked collaboration remained accessible');
  await assert.rejects(rpc('catalog',{},'/desktop-collab'),/注册中继/);
  assert.deepEqual(await rpc('draft-get',{key:'registration-fixture'},'/desktop-collab'),{body:'Keep across unregister'});
  assert.equal((await rpc('state',{},'/desktop-collab')).peer.id,identityBeforeRevocation);
  report.checks.push('Unregistering removes the open workspace and blocks relay requests while preserving the local identity and draft');
}
app.setAppPath(root);
void boot();
