const { app, BrowserWindow, ipcMain } = require('electron');
const assert = require('node:assert/strict');
const { join } = require('node:path');
const { mkdirSync, mkdtempSync, writeFileSync, readFileSync } = require('node:fs');
const { createServer } = require('node:http');
const { randomUUID } = require('node:crypto');
const { spawn } = require('node:child_process');
const { createInterface } = require('node:readline');
const root = join(__dirname, '..');
mkdirSync(join(root, '.test-data'), { recursive: true });
const data = mkdtempSync(join(root, '.test-data/collaboration-native-'));
process.env.DSH_DESKTOP_DATA_DIR = data;
process.env.DSH_DESKTOP_CONFIG_HOME = join(data, 'core');
process.env.DSH_TELEMETRY_DISABLED = '1';
process.env.DSH_COLLAB_FIXTURE_REJECT_WS = '1';
process.env.DSH_COLLAB_FIXTURE_KEY = 'isolated-local-fixture';
app.commandLine.appendSwitch('use-fake-device-for-media-stream');
app.commandLine.appendSwitch('use-fake-ui-for-media-stream');
const relay = spawn(join(root, '.runtime/bin', process.platform === 'win32' ? 'node.exe' : 'node'), ['services/relay/node_modules/tsx/dist/cli.mjs', 'services/relay/test/collab-fixture.ts'], { cwd: root, stdio: ['pipe', 'pipe', 'inherit'] });
const fixture = new Promise((resolve, reject) => { createInterface({ input: relay.stdout }).once('line', line => resolve(JSON.parse(line))); relay.once('error', reject); });
let modelCalls = 0;
const model = createServer(async (req, res) => {
  if (req.url?.endsWith('/models')) { res.setHeader('content-type', 'application/json'); res.end(JSON.stringify({ data: [{ id: 'deepseek-flash', object: 'model' }] })); return; }
  if (!req.url?.endsWith('/messages')) { res.writeHead(404); res.end('{}'); return; }
  let body = ''; for await (const chunk of req) body += chunk;
  const input = JSON.parse(body); modelCalls++;
  // The deterministic model fixture supplies outputs only inside its own disposable run.
  const profile = JSON.parse(readFileSync(join(data, 'core/collaboration/profile.json')));
  const run = Object.values(profile.runs).sort((a, b) => b.startedAt - a.startedAt)[0];
  const cwd = join(data, 'core/collaboration/workspaces', run.id);
  const answer = '# AI 生成方案\n\n使用 `42` 验证。\n\n```python\nprint(42)\n```\n\n| 项目 | 结果 |\n| --- | --- |\n| 检查 | 通过 |\n\n附件：`generated.png`、`result.txt`。';
  writeFileSync(join(cwd, 'result.txt'), 'Fixture output');
  writeFileSync(join(cwd, 'generated.png'), Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1kAAAAASUVORK5CYII=', 'base64'));
  writeFileSync(join(cwd, 'submission.json'), JSON.stringify({ body: answer, verification: 'Isolated fixture', limitations: 'No production model', files: ['generated.png', 'result.txt'] }));
  const usage = { input_tokens: 128, output_tokens: 32 }, message = { id: randomUUID(), type: 'message', role: 'assistant', model: input.model, content: [{ type: 'text', text: answer }], stop_reason: 'end_turn', usage };
  if (!input.stream) { res.setHeader('content-type', 'application/json'); res.end(JSON.stringify(message)); return; }
  res.writeHead(200, { 'content-type': 'text/event-stream' });
  const emit = (type, value) => res.write(`event: ${type}\ndata: ${JSON.stringify({ type, ...value })}\n\n`);
  emit('message_start', { message: { ...message, content: [], stop_reason: null, usage: { ...usage, output_tokens: 0 } } });
  emit('content_block_start', { index: 0, content_block: { type: 'text', text: '' } }); emit('content_block_delta', { index: 0, delta: { type: 'text_delta', text: answer } });
  emit('content_block_stop', { index: 0 }); emit('message_delta', { delta: { stop_reason: 'end_turn' }, usage: { output_tokens: 32 } }); emit('message_stop', {}); res.end();
});
async function boot() {
  await new Promise(resolve => model.listen(0, '127.0.0.1', resolve));
  mkdirSync(join(data, 'core'), { recursive: true });
  writeFileSync(join(data, 'core/desktop.patch.yml'), `- id: llm-deepseek\n  config:\n    baseURL: http://127.0.0.1:${model.address().port}\n    apiKeyEnv: DSH_COLLAB_FIXTURE_KEY\n    maxTokens: 4096\n`);
  writeFileSync(join(data, 'core/settings.yaml'), 'agent-default-model:\n  provider: deepseek-official\n  model: deepseek-flash\n');
  require(join(root, 'dist/main/index.cjs'));
}
const report = { checks: [], errors: [], console: [], data };
let finished = false, started = false;
const timer = setTimeout(() => finish(new Error('Collaboration UI timeout')), 120000);
function finish(error) {
  if (finished) return; finished = true; clearTimeout(timer);
  if (error) report.errors.push(String(error.stack ?? error));
  writeFileSync(join(data, 'report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2)); relay.stdin.end(); model.close(); app.quit();
}
app.on('quit', () => { relay.stdin.end(); if (report.errors.length) process.exit(1); });
app.on('web-contents-created', (_, contents) => contents.on('console-message', details => { if (details.level === 'error') report.console.push(details.message); }));
const handlers = new Map(), original = ipcMain.handle.bind(ipcMain);
ipcMain.handle = (channel, callback) => { handlers.set(channel, callback); return original(channel, async (...args) => {
  const result = await callback(...args);
  if (channel === 'desktop:ready' && !started) { started = true; setTimeout(() => run(args[0]).then(() => finish()).catch(async error => {
    report.ui = await args[0].sender.executeJavaScript('document.body.innerText.slice(0,14000)').catch(() => ''); finish(error);
  }), 100); }
  return result;
}); };
async function run(event) {
  const contents = event.sender, window = BrowserWindow.fromWebContents(contents), js = code => contents.executeJavaScript(code, true);
  window.setSize(1220, 900); contents.setBackgroundThrottling(false);
  const until = async (check, message) => { const start = Date.now(); while (Date.now() - start < 20000) { if (await check()) return; await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(message); };
  const click = text => js(`(() => {const b=Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim()===${JSON.stringify(text)}); if(!b)throw Error('Button missing: '+${JSON.stringify(text)}); b.click();})()`);
  const rpc = (method, args = {}, channel = '/api') => js(`(async()=>{const method=${JSON.stringify(method)},rpcId=crypto.randomUUID(); const r=await fetch(${JSON.stringify(channel + '/' + method)},{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'client-request',rpcId,method,payload:{args:${JSON.stringify(args)}}})});const body=await r.json(); if(!body.result.ok)throw Error(JSON.stringify(body.result.error));return body.result.value;})()`);
  const fill = (selector, value) => js(`(async () => {const el=document.querySelector(${JSON.stringify(selector)}); if(!el)throw Error('Input missing');const proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>requestAnimationFrame(r));})()`);
  const attach = (selector, files) => js(`(() => {const input=document.querySelector(${JSON.stringify(selector)}); if(!input)throw Error('Upload input missing');const list=new DataTransfer();for(const f of ${JSON.stringify(files)}){const bytes=f.base64?Uint8Array.from(atob(f.base64),c=>c.charCodeAt(0)):f.size?new Uint8Array(f.size):f.text;list.items.add(new File([bytes],f.name,{type:f.type||'application/octet-stream'}));}input.files=list.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1kAAAAASUVORK5CYII=';
  await until(() => js(`(() => {const b=Array.from(document.querySelectorAll('button')).find(b=>['继续','Continue','稍后配置','Configure later'].includes(b.textContent));if(b){if(!b.disabled)b.click();return false;}return document.getElementById('root')?.inert===false&&!!document.querySelector('[contenteditable="true"][data-phase="plain"]');})()`), 'Initial UI did not become ready');
  const f = await fixture;
  const stats = async () => (await fetch(f.origin + '/__fixture/status')).json();
  const act = action => handlers.get('desktop:remote-action')(event, action);
  await act({ type: 'configure', config: { relay: f.origin, name: 'Collaboration UI fixture', enabled: false, background: true, sessionOnly: true } });
  await act({ type: 'register', code: f.code });
  const bundles = await rpc('pluginManager/listBundles');
  assert.equal(bundles.find(b => b.name === 'dsh-p2p-collab').enabled, false);
  await click('插件');
  await until(() => js(`!!document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]')`), 'Bundled collaboration plugin is missing from Plugins while disabled');
  assert.equal(await js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]').getAttribute('aria-checked')`), 'false');
  await js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]').click()`);
  await until(() => js(`Array.from(document.querySelectorAll('button')).some(b=>b.textContent.trim()==='协作空间')`), 'Collaboration sidebar entry missing');
  report.checks.push('Bundled collaboration plugin is visible while disabled and can be enabled through its actual Plugins switch');
  await click('协作空间');
  await until(() => js(`!!document.querySelector('[data-testid="collab-page"] .collab-task')`), 'Task catalog did not render');
  await until(async () => !!(await rpc('state', {}, '/desktop-collab')).lastSyncAt, 'HTTP message refresh did not complete');
  assert.equal(await js(`!!document.querySelector('.collab-connection')`), false, 'Collaboration must not display connection presence');
  await click('设置');
  await fill('[aria-label="单次任务 Token 停止阈值"]', '100000000');
  await fill('[aria-label="最长运行时间（分钟）"]', '43200'); await click('保存设置');
  await until(() => js(`document.querySelector('[aria-label="协作设置"] [role="status"]')?.textContent==='已保存'`), 'Large budgets did not save');
  assert.deepEqual((await rpc('state', {}, '/desktop-collab')).settings, { maxTokens: 100000000, maxMinutes: 43200, publishMode: 'review' });
  await fill('[aria-label="单次任务 Token 停止阈值"]', '-1'); await click('保存设置');
  await until(() => js(`document.querySelector('[aria-label="协作设置"] [role="status"]')?.textContent.includes('非负整数')`), 'Budget validation did not show a readable error');
  await fill('[aria-label="单次任务 Token 停止阈值"]', '100000000'); await click('保存设置');
  await until(() => js(`document.querySelector('[aria-label="协作设置"] [role="status"]')?.textContent==='已保存'`), 'Budget correction did not save');
  writeFileSync(join(data, 'large-budget-settings.png'), (await contents.capturePage()).toPNG());
  await click('任务广场'); await until(() => js(`!!document.querySelector('.collab-task')`), 'Catalog did not return');
  await js(`document.querySelector('.collab-task').click()`);
  await until(() => js(`!!document.querySelector('[data-collab-detail]')`), 'Task detail did not open');
  assert.ok((await js('document.querySelector(".collab-detail").innerText')).includes('验证协作中的缓存 Token 统计'));
  assert.ok((await rpc('state', {}, '/desktop-collab')).runs.length === 0);
  await click('关注任务'); await until(() => js(`document.querySelector('.collab-detail').innerText.includes('取消关注')`), 'Follow did not persist');
  await click('← 返回列表');
  assert.equal((await fetch(f.origin + '/__fixture/peer-reply', { method: 'POST' })).status, 200, 'Peer fixture reply failed');
  await click('刷新消息');
  await until(() => js(`Array.from(document.querySelectorAll('.collab-tabs button')).some(b=>b.textContent.startsWith('消息 ('))`), 'Manual HTTP refresh did not receive another peer reply');
  await js(`Array.from(document.querySelectorAll('.collab-tabs button')).find(b=>b.textContent.startsWith('消息')).click()`);
  await until(() => js(`!!document.querySelector('.collab-task.unread')`), 'Unread message did not render');
  await js(`document.querySelector('.collab-task.unread').click()`);
  await until(() => js(`document.querySelector('.collab-thread')?.innerText.includes('另一个节点已补充复现信息。')`), 'Received reply did not open');
  await js(`(() => {
    const original = window.fetch.bind(window); window.__collabVoice = { calls: 0, replies: 0, wave: false };
    window.__restoreCollabFetch = () => { window.fetch = original; };
    window.fetch = async (input, init) => {
      const url = String(input);
      if (url.endsWith('desktop-collab/reply')) window.__collabVoice.replies++;
      if (!url.endsWith('api/speech/catalog') && !url.endsWith('api/speech/transcribe')) return original(input, init);
      const request = JSON.parse(init.body); let value;
      if (url.endsWith('/catalog')) value = { providers: [{ id: 'fixture', preparation: { phase: 'ready' } }], selection: { providerId: 'fixture', language: 'zh' }, maxAudioBytes: 1048576, maxDurationSeconds: 10 };
      else { window.__collabVoice.calls++; window.__collabVoice.wave = atob(request.payload.args.request.audioBase64).startsWith('RIFF'); value = { text: '语音只追加到草稿' }; }
      return new Response(JSON.stringify({ type: 'server-response', rpcId: request.rpcId, result: { ok: true, value } }), { headers: { 'content-type': 'application/json' } });
    };
  })()`);
  await fill('[aria-label="回复任务"] textarea', '已输入的草稿');
  await js(`document.querySelector('[aria-label="语音输入：回复内容"]').click()`);
  await until(() => js(`!!document.querySelector('[aria-label="结束：回复内容"]')`), 'Collaboration microphone did not start');
  await new Promise(resolve => setTimeout(resolve, 450));
  await js(`document.querySelector('[aria-label="结束：回复内容"]').click()`);
  await until(() => js(`document.querySelector('[aria-label="回复任务"] textarea').value.includes('语音只追加到草稿')`), 'Speech transcript did not append');
  assert.deepEqual(await js('window.__collabVoice'), { calls: 1, replies: 0, wave: true });
  assert.ok((await js(`document.querySelector('[aria-label="回复任务"] textarea').value`)).startsWith('已输入的草稿'));
  await js('window.__restoreCollabFetch()');
  report.checks.push('Collaboration microphone captures a fake Chromium device, sends PCM WAV to a stub speech service and appends text without publishing');
  await fill('[aria-label="回复任务"] textarea', '本机用户确认：正在补充复现条件。 https://example.com/shared-artifact.zip');
  await attach('[aria-label="回复任务"] input[type="file"]', [{ name: 'not-uploaded.txt', text: 'valid file before oversized file' }, { name: 'too-large.zip', size: 8 * 1024 * 1024 + 1 }]);
  await until(() => js(`document.querySelector('[aria-label="回复任务"] [role="alert"]')?.textContent.includes('下载链接')`), 'Oversized reply attachment did not suggest a link');
  assert.equal((await stats()).attachmentUploads, 0, 'Oversized selection must fail before uploading any member');
  await attach('[aria-label="回复任务"] input[type="file"]', [{ name: 'reply-image.png', base64: png, type: 'image/png' }, { name: 'boundary-8MiB.bin', size: 8 * 1024 * 1024 }]);
  await until(() => js(`document.querySelectorAll('[aria-label="回复任务"] .collab-upload > span').length===2`), 'Valid reply image and 8 MiB boundary attachment did not upload');
  await fetch(f.origin + '/__fixture/drop-next-reply', { method: 'POST' });
  await click('发送回复');
  await until(() => js(`document.querySelector('[aria-label="回复任务"] [role="alert"]')?.textContent.includes('fixture_response_lost')`), 'Lost response did not report an unconfirmed send');
  assert.ok((await js(`document.querySelector('[aria-label="回复任务"] textarea').value`)).includes('正在补充复现条件'));
  assert.equal(await js(`document.querySelectorAll('[aria-label="回复任务"] .collab-upload > span').length`), 2);
  await click('发送回复');
  await until(() => js(`document.querySelector('.collab-thread').innerText.includes('本机用户确认：正在补充复现条件。')`), 'Human reply did not appear');
  assert.equal((await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).replies.filter(r => r.body.includes('本机用户确认')).length, 1, 'Retry after a lost response duplicated the reply');
  assert.equal(await js(`document.querySelector('.collab-thread a')?.getAttribute('href')`), 'https://example.com/shared-artifact.zip');
  await js(`document.querySelector('[aria-label="预览图片 reply-image.png"]').click()`);
  await until(() => js(`document.querySelector('.collab-thread img')?.naturalWidth>0`), 'Uploaded reply image preview did not render');
  writeFileSync(join(data, 'reply-attachments.png'), (await contents.capturePage()).toPNG());
  await click('一键 AI 求解并提交');
  await until(() => js(`document.querySelector('[aria-label="回复任务"] textarea')?.value.includes('# AI 生成方案')`), 'Reviewed AI result did not automatically populate the editor');
  assert.equal((await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).replies.filter(r => r.actor === 'dsh').length, 0, 'Review mode published before review');
  assert.equal(await js(`document.querySelectorAll('[aria-label="AI 生成附件"] > span').length`), 2);
  await js(`document.querySelector('[aria-label="移除 result.txt"]').click()`);
  await fill('[aria-label="回复任务"] textarea', '# 人工审核后的方案\n\n已修改 AI 正文，保留图片附件。');
  await click('发布方案');
  await until(() => js(`document.querySelector('.collab-thread')?.innerText.includes('人工审核后的方案')`), 'Reviewed AI result did not publish');
  const reviewed = (await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).replies.find(r => r.body.includes('人工审核后的方案'));
  assert.deepEqual(reviewed.attachments.map(file => file.name), ['generated.png']);
  assert.equal(reviewed.actor, 'dsh');
  await click('设置');
  await js(`document.querySelector('input[name="collab-publish-mode"][value="auto"]').click()`); await click('保存设置');
  await until(async () => (await rpc('state', {}, '/desktop-collab')).settings.publishMode === 'auto', 'Auto mode did not save');
  await click('任务广场'); await until(() => js(`!!document.querySelector('.collab-task')`), 'Catalog missing'); await js(`document.querySelector('.collab-task').click()`);
  await until(() => js(`document.querySelector('.collab-detail')?.innerText.includes('当前为 AI 自动发布')`), 'Auto mode explanation missing');
  await click('一键 AI 回复');
  await until(() => js(`document.querySelector('.collab-detail')?.innerText.includes('AI 已自动发布正文和附件')`), 'AI did not auto publish');
  const automatic = (await rpc('detail', { taskId: f.taskId }, '/desktop-collab')).replies.filter(r => r.body.includes('# AI 生成方案'));
  assert.equal(automatic.length, 1); assert.equal(automatic[0].attachments.length, 2);
  await until(() => js(`!!document.querySelector('.collab-thread .collab-prose table')`), 'Markdown table did not render');
  assert.ok(await js(`Array.from(document.querySelectorAll('.collab-thread .collab-prose code')).some(e=>e.textContent.includes('print(42)'))`), 'Fenced Python code did not render');
  assert.equal(modelCalls, 2);
  await js(`Array.from(document.querySelectorAll('.collab-thread .collab-reply')).at(-1).scrollIntoView({block:'start'})`);
  await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
  writeFileSync(join(data, 'markdown-ai-solution.png'), (await contents.capturePage()).toPNG());
  await click('设置'); await js(`document.querySelector('input[name="collab-publish-mode"][value="manual"]').click()`); await click('保存设置');
  await until(async () => (await rpc('state', {}, '/desktop-collab')).settings.publishMode === 'manual', 'Manual mode did not save');
  await click('任务广场'); await until(() => js(`!!document.querySelector('.collab-task')`), 'Catalog missing'); await js(`document.querySelector('.collab-task').click()`);
  await until(() => js(`!!document.querySelector('[aria-label="回复任务"] textarea')`), 'Manual reply composer missing');
  assert.equal(await js(`Array.from(document.querySelectorAll('.collab-detail button')).some(b=>b.textContent==='一键 AI 回复')`), false);
  report.checks.push('Review mode fills editable Markdown and generated files; reviewer edits text and removes an attachment; auto mode publishes exactly once with files; manual mode hides AI actions');
  await click('发布任务');
  await until(() => js(`!!document.querySelector('[aria-label="发布任务"] textarea:not(:disabled)')`), 'Task composer did not load');
  assert.equal(await js(`document.querySelector('[aria-label="发布任务"] details').open`), false);
  await fill('[aria-label="发布任务"] textarea', '可复现的协作任务\n\n测试任务描述：请检查界面、草稿和版本记录。');
  const uploadsBeforeTask = (await stats()).attachmentUploads;
  await attach('[aria-label="发布任务"] input[type="file"]', Array.from({ length: 9 }, (_, i) => ({ name: `file-${i}.txt`, text: 'fixture' })));
  await until(() => js(`document.querySelector('[aria-label="发布任务"] [role="alert"]')?.textContent.includes('最多附带 8 个')`), 'Attachment count limit missing');
  assert.equal((await stats()).attachmentUploads, uploadsBeforeTask);
  await attach('[aria-label="发布任务"] input[type="file"]', [{ name: 'task-image.png', base64: png, type: 'image/png' }, { name: 'reproduction.txt', text: 'Reproduction attachment' }]);
  await until(() => js(`document.querySelectorAll('[aria-label="发布任务"] .collab-upload > span').length===2`), 'Task attachments did not upload');
  await until(() => js(`Array.from(document.querySelectorAll('[aria-label="发布任务"] button')).some(b=>b.textContent==='发布任务'&&!b.disabled)`), 'Publish button stayed disabled');
  await js(`Array.from(document.querySelectorAll('[aria-label="发布任务"] button')).find(b=>b.textContent==='发布任务').click()`);
  await until(() => js(`document.querySelector('[data-collab-detail] h1')?.textContent==='可复现的协作任务'`), 'Published task did not open');
  await js(`document.querySelector('[aria-label="预览图片 task-image.png"]').click()`);
  await until(() => js(`document.querySelector('.collab-detail > section img')?.naturalWidth>0`), 'Task image preview did not render');
  await click('编辑任务');
  await fill('[aria-label="编辑任务"] textarea', '已补充验收数据，保留第一版内容。');
  await click('保存新版本');
  await until(() => js(`document.querySelector('.collab-detail').innerText.includes('版本 2')`), 'Revision did not update');
  await click('修改记录');
  await until(() => js(`document.querySelector('.collab-detail').innerText.includes('最近 20 个版本')`), 'Revision history missing');
  assert.ok((await js(`Array.from(document.querySelectorAll('.collab-detail details')).map(e=>e.textContent).join(' ')`)).includes('测试任务描述：请检查界面、草稿和版本记录。'));
  const bounds = await js(`(()=>{const e=document.querySelector('.collab');return {width:e.clientWidth,scroll:e.scrollWidth,height:e.clientHeight};})()`);
  assert.ok(bounds.scroll <= bounds.width + 1, 'Collaboration page overflows horizontally');
  window.show(); window.focus();
  await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
  writeFileSync(join(data, 'task-detail.png'), (await contents.capturePage()).toPNG());
  await click('任务广场');
  await until(() => js(`document.querySelectorAll('.collab-task').length===2`), 'Catalog did not refresh after publish');
  await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
  writeFileSync(join(data, 'task-catalog.png'), (await contents.capturePage()).toPNG());
  report.checks.push('Task publishing, author editing, preserved revision history and refreshed catalog pass in actual Electron UI; screenshots captured without horizontal overflow');
  assert.equal((await stats()).collaborationUpgrades, 0);
  report.checks.push('100 million Token / 30-day budgets save; HTTP-only manual inbox refresh receives peer replies while collaboration WebSocket is rejected');
  report.checks.push('Task/reply images and attachments upload and preview; exact 8 MiB upload succeeds; oversized batch and ninth file are rejected before upload; a lost reply response preserves its draft and retry creates one reply');
  await click('插件');
  await until(() => js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]')?.getAttribute('aria-checked')==='true'`), 'Enabled collaboration switch missing');
  await js(`document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"]').click()`);
  await until(async () => !(await rpc('pluginManager/listBundles')).find(b => b.name === 'dsh-p2p-collab').enabled, 'Plugin did not disable');
  await until(() => js(`!!document.querySelector('[data-plugin-package="dsh-p2p-collab"] [role="switch"][aria-checked="false"]')&&!Array.from(document.querySelectorAll('button')).some(b=>b.textContent.trim()==='协作空间')`), 'Disabled plugin disappeared from Plugins or left an active sidebar');
  report.checks.push('Actual Plugins switch disables collaboration and retains its card for later re-enabling');
}
app.setAppPath(root);
void boot();
